package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SystemTests_E2eTeamCityTestOnEc2'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SystemTests_E2eTeamCityTestOnEc2")) {
    dependencies {
        expect(RelativeId("BuildDistTarGzWar")) {
            artifacts {
                id = "ARTIFACT_DEPENDENCY_7010"
                artifactRules = "TeamCity*.tar.gz=>%teamcity.distrib%"
            }
        }
        update(RelativeId("BuildDistTarGzWar")) {
            artifacts {
                id = "ARTIFACT_DEPENDENCY_7010"
                buildRule = lastSuccessful()
                artifactRules = "TeamCity*.tar.gz=>%teamcity.distrib%"
            }
        }

    }
}
